[package]
name = "grex_t0"
version = "0.4.0"
edition = "2021"

[dependencies]
anyhow = "1"
casperfpga = { git = "https://github.com/kiranshila/casperfpga_rs", version = "0.1.0" }
casperfpga_derive = { git = "https://github.com/kiranshila/casperfpga_rs", version = "0.1.0" }
chrono = "0.4"
clap = { version = "=4.0", features = ["derive"] }
clap_lex = "=0.3.0"
fixed = "1.21.0"
hdf5 = "0.8"
http-body-util = "0.1.0-rc.2"
hyper = { version = "1.0.0-rc.2", features = ["full"] }
lazy_static = "1.4"
log = "0.4"
prometheus = "0.13"
ndarray = "0.15"
num-complex = "0.4"
pretty_env_logger = "0.4"
regex = "1"
rsntp = "3"
socket2 = "0.4"
tokio = { version = "1.15", features = ["full", "tracing"] }
thiserror = "1"
thingbuf = "0.1"
core_affinity = "0.8"
console-subscriber = "0.1"
psrdada = "0.2"
byte-slice-cast = "1"
lending-iterator = "0.1.6"

[lib]
name = "grex_t0"
path = "src/lib.rs"

[[bin]]
name = "grex_t0"
path = "src/main.rs"

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
debug = 1
panic = "abort"

[dev-dependencies]
criterion = "0.4"
rand = "0.8"
