[package]
name = "grex-t0"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "=4.0.0", features = ["derive"] }
num-complex = { version = "0.4", features = ["rand"] }
pcap = "1"
tui = "0.19"
crossterm = "0.25"
crossbeam-channel = "0.5"
